---
- name: set up sources
  hosts: all
  tags: casks
  tasks:
  - name: get homebrew taps setup
    homebrew_tap: tap={{ item }} state=present
    always_run: yes
    with_items:
      - homebrew/binary

- name: essential tools for shell environment
  hosts: all
  tags: essential
  tasks:
  - name: install essential shell brews
    homebrew: name={{ item }} state=present
    with_items:
      - git
      - hub
      - scmpuff
      - ssh-copy-id
      - imagemagick

  - name: remove legacy shell brews
    homebrew: name={{ item }} state=absent
    with_items:
      - gh #gh is now hub

  - name: install essential shell casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - xquartz


# Manually include the development playbooks here for reverse compatibility
# Probably will change the overall structure of things soon though...
- import_playbook: playbooks/development.yml

- name: Applications and tools
  hosts: all
  tasks:
  - name: install brewcask applications
    tags: casks
    homebrew_cask: state=present name={{ item }}
    with_items:
      # webdevs need all the webs (except opera lol)
      - google-chrome
      - firefox
      # text editors i hate the least
      - atom
      - macvim
      - mou
      # virtual machines
      - vmware-fusion
      # other dev tools
      - dash
      - github-desktop
      # non-dev stuff for general productivity
      - caffeine
      - cloud
      - daisydisk
      - dropbox
      - flux
      # non-dev stuff for general unproductivity
      - steam
      - transmission
      - vlc

  - name: install homebrew tools
    tags: brews
    homebrew: state=present name={{ item }}
    with_items:
      # dev tools
      - ack
      - jq
      - gist
      # text editor assistance
      - ctags
      - shellcheck
      # heroku style development
      - heroku-toolbelt
      - forego
      # networking tools
      - curl
      - wget
      - speedtest_cli
      # security tools
      - keybase
      - gnupg
      - nmap
      - pwgen
      # media related tools
      - pianobar
      - ffmpeg
