---
- name: Rust Development Environment
  hosts: all
  tags: rust

  tasks:
    - name: install homebrew stub for rustup
      homebrew: name=rustup-init state=present

    # TODO: rustup-init -y --no-modify-path
